name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          # Required, playbook filepath
          playbook: deploy.yml
          # Optional, directory where playbooks live
          directory: ./playbooks
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            server ansible_host=${{ vars.SSH_HOST }} ansible_user=${{ vars.SSH_USER }}

          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory .hosts
            --extra-vars "image_name=${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}"
            --extra-vars "domain_name=${{ vars.DOMAIN_NAME }}"
            --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
            --verbose
